import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { LuSparkles, LuWallet, LuUsers, LuMapPin, LuPackage, LuMail, LuScale, LuCar, LuTrendingUp } from 'react-icons/lu';
import { FiCheckSquare, FiStar, FiCalendar } from 'react-icons/fi';
import api from '../../utils/api';

const tools = [
  {
    id: 'ai-planner',
    title: 'AI Wedding Planner',
    description: 'Personalized wedding roadmap, vendor suggestions, and timelines generated by AI.',
    icon: <LuSparkles />,
    path: '/tools/ai-planner',
    color: 'from-purple-500 to-indigo-500',
    bg: 'bg-purple-50',
    text: 'text-purple-600'
  },
  {
    id: 'budget-planner',
    title: 'Budget Planner',
    description: 'Auto-allocate your budget across venues, catering, photography, and more.',
    icon: <LuWallet />,
    path: '/tools/budget-planner',
    color: 'from-[#C2185B] to-[#8E244D]',
    bg: 'bg-pink-50',
    text: 'text-[#C2185B]'
  },
  {
    id: 'guest-manager',
    title: 'Guest List Manager',
    description: 'Track RSVPs, manage invitations, and organize your guests effortlessly.',
    icon: <LuUsers />,
    path: '/tools/guest-manager',
    color: 'from-blue-500 to-cyan-500',
    bg: 'bg-blue-50',
    text: 'text-blue-600'
  },
  {
    id: 'checklist',
    title: 'Wedding Checklist',
    description: 'Dynamic task management to track your wedding readiness percentage.',
    icon: <FiCheckSquare />,
    path: '/tools/checklist',
    color: 'from-emerald-500 to-teal-500',
    bg: 'bg-emerald-50',
    text: 'text-emerald-600'
  },
  {
    id: 'vendor-availability',
    title: 'Vendor Availability',
    description: 'Check real-time availability of vendors for your specific dates and location.',
    icon: <LuMapPin />,
    path: '/tools/vendor-availability',
    color: 'from-amber-500 to-orange-500',
    bg: 'bg-amber-50',
    text: 'text-amber-600'
  },
  {
    id: 'package-builder',
    title: 'Package Builder',
    description: 'Select multiple services and generate a customized wedding package instantly.',
    icon: <LuPackage />,
    path: '/tools/package-builder',
    color: 'from-rose-500 to-pink-500',
    bg: 'bg-rose-50',
    text: 'text-rose-600'
  },
  {
    id: 'invitation-generator',
    title: 'Invitation Generator',
    description: 'Create, preview, and share dynamic wedding invitations via WhatsApp.',
    icon: <LuMail />,
    path: '/tools/invitation-generator',
    color: 'from-[#D4AF37] to-yellow-500',
    bg: 'bg-yellow-50',
    text: 'text-[#D4AF37]'
  },
  {
    id: 'vendor-compare',
    title: 'Vendor Comparison',
    description: 'Compare vendors side-by-side by price, ratings, experience, and packages.',
    icon: <LuScale />,
    path: '/tools/vendor-compare',
    color: 'from-slate-500 to-gray-500',
    bg: 'bg-slate-50',
    text: 'text-slate-600'
  },
  {
    id: 'baraat-calculator',
    title: 'Baraat Fleet Calculator',
    description: 'Estimate fleet requirements and costs based on your guest count.',
    icon: <LuCar />,
    path: '/tools/baraat-calculator',
    color: 'from-red-500 to-rose-600',
    bg: 'bg-red-50',
    text: 'text-red-600'
  },
  {
    id: 'cost-predictor',
    title: 'Cost Predictor',
    description: 'Predict estimated wedding costs based on location, guest count, and type.',
    icon: <LuTrendingUp />,
    path: '/tools/cost-predictor',
    color: 'from-green-500 to-emerald-600',
    bg: 'bg-green-50',
    text: 'text-green-600'
  },
  {
    id: 'kundli-matching',
    title: 'Kundli Matching',
    description: 'Check celestial compatibility with Vedic Ashta Koota Gun Milan.',
    icon: <FiStar />,
    path: '/tools/kundli-matching',
    color: 'from-[#1a1a1a] to-[#2d2d2d]',
    bg: 'bg-gray-900',
    text: 'text-[#D4AF37]'
  },
  {
    id: 'muhurat-finder',
    title: 'Shubh Muhurat Finder',
    description: 'Discover the most auspicious dates and timings for your wedding ceremonies.',
    icon: <FiCalendar />,
    path: '/tools/muhurat-finder',
    color: 'from-amber-400 to-orange-400',
    bg: 'bg-orange-50',
    text: 'text-orange-500'
  }
];

export default function ToolsHubPage() {
  
  useEffect(() => {
    // Log entry to tools hub
    api.post('/tools/track', { toolName: 'Tools Hub', action: 'viewed_hub' }).catch(() => {});
  }, []);

  return (
    <div className="min-h-screen bg-[#FFF8F0]/50 pt-24 pb-20 font-sans">
      <div className="absolute inset-0 floral-pattern opacity-[0.03] pointer-events-none" />
      <div className="max-w-7xl mx-auto px-4 relative z-10">
        
        {/* Header */}
        <div className="text-center mb-16 relative">
          <motion.div initial={{ opacity: 0, scale: 0.8 }} animate={{ opacity: 1, scale: 1 }} className="inline-flex items-center justify-center px-4 py-2 bg-[#D4AF37]/10 text-[#D4AF37] rounded-full text-[10px] font-black uppercase tracking-widest mb-6 border border-[#D4AF37]/20">
            Premium Features
          </motion.div>
          <motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="text-4xl md:text-6xl font-display font-black text-gray-900 mb-6 tracking-tight drop-shadow-sm">
            Wedding <span className="text-[#C2185B]">Tools Hub</span>
          </motion.h1>
          <motion.p initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="text-gray-500 text-lg font-medium italic max-w-2xl mx-auto leading-relaxed">
            Everything you need to plan your dream wedding. Use our suite of AI-powered tools to manage your budget, guests, vendors, and more.
          </motion.p>
        </div>

        {/* Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {tools.map((tool, idx) => (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.05 }}
              key={tool.id}
            >
              <Link to={tool.path} className="bg-white rounded-[2rem] p-6 shadow-sm hover:shadow-premium border border-pink-50 transition-all duration-300 group flex flex-col h-full hover:-translate-y-1 relative overflow-hidden">
                <div className={`absolute top-0 right-0 w-32 h-32 rounded-bl-full opacity-10 bg-gradient-to-br ${tool.color} pointer-events-none group-hover:scale-110 transition-transform duration-500`} />
                
                <div className={`w-14 h-14 rounded-2xl flex items-center justify-center text-2xl mb-6 shadow-inner ${tool.bg} ${tool.text} group-hover:scale-110 transition-transform duration-300 relative z-10`}>
                  {tool.icon}
                </div>
                
                <h3 className="font-display text-xl font-black text-gray-900 mb-2 relative z-10 group-hover:text-[#C2185B] transition-colors">{tool.title}</h3>
                <p className="text-sm text-gray-500 font-medium italic leading-relaxed flex-grow relative z-10">{tool.description}</p>
                
                <div className="mt-6 pt-4 border-t border-gray-50 flex items-center justify-between relative z-10">
                  <span className="text-[10px] font-black uppercase tracking-widest text-gray-400 group-hover:text-[#C2185B] transition-colors">Launch Tool</span>
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center bg-gray-50 group-hover:bg-[#C2185B] text-gray-400 group-hover:text-white transition-colors`}>
                    →
                  </div>
                </div>
              </Link>
            </motion.div>
          ))}
        </div>

      </div>
    </div>
  );
}
